// codegen: 扫描 packages/zai/src/shared/rpc.ts 的 RpcMethodMap interface,
// 生成 packages/zai/src/web/src/lib/api.generated.ts.
//
// SPEC: docs/superpowers/specs/2026-08-16-rpc-type-safe-client-stubs.md
//
// 命名约定:
//   'POST /api/agent/command' → api.agent.command.post(body)
//   'GET /api/cli'             → api.cli.get()
//   'GET /api/health'          → api.health.get()
//
// 限制:
// - 当前实现不支持 path 含动态参数 (`:id` 等) — 含 :id 的 entry 会被
//   skip 并 warn。迁移这些 route 时单独处理 (e.g. 加 helper `withPathId`).
// - 仅扫 `RpcMethodMap` interface; 加新 interface 不会被自动捕获。

import { readFile, writeFile } from 'node:fs/promises'
import { resolve, dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import ts from 'typescript'

const __dirname = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(__dirname, '..')

const rpcPath = resolve(repoRoot, 'packages/zai/src/shared/rpc.ts')
const outPath = resolve(repoRoot, 'packages/zai/src/web/src/lib/api.generated.ts')

interface Entry {
  method: string
  path: string
  requestType: string
  responseType: string
}

async function main() {
  const source = await readFile(rpcPath, 'utf-8')
  const sf = ts.createSourceFile(rpcPath, source, ts.ScriptTarget.ESNext, true)

  // 定位 interface RpcMethodMap
  const iface = sf.statements.find(
    (st) => ts.isInterfaceDeclaration(st) && st.name.text === 'RpcMethodMap',
  ) as ts.InterfaceDeclaration | undefined
  if (!iface) {
    throw new Error('RpcMethodMap interface not found in ' + rpcPath)
  }

  const entries: Entry[] = []
  const skipped: Array<{ key: string; reason: string }> = []

  for (const member of iface.members) {
    if (!ts.isPropertySignature(member) || !member.name || !ts.isStringLiteral(member.name)) {
      continue
    }
    const key = member.name.text
    const [method, path] = key.split(' ')
    if (!method || !path) {
      console.warn(`[codegen] skip ${key}: 格式非 "<METHOD> <path>"`)
      continue
    }
    if (!member.type || !ts.isTypeLiteralNode(member.type)) {
      console.warn(`[codegen] skip ${key}: type 不是 type literal — 当前 codegen 只支持 inline { request: T; response: U }`)
      continue
    }
    let requestType = 'undefined'
    let responseType = 'undefined'
    for (const prop of member.type.members) {
      if (!ts.isPropertySignature(prop) || !prop.name || !ts.isIdentifier(prop.name)) continue
      const propName = prop.name.text
      const propType = prop.type ? prop.type.getText(sf) : 'unknown'
      if (propName === 'request') requestType = propType
      else if (propName === 'response') responseType = propType
    }
    if (path.includes(':')) {
      skipped.push({ key, reason: 'path 含动态参数 (:id) — 暂不支持, 后续单独处理' })
      continue
    }
    entries.push({ method, path, requestType, responseType })
  }

  // 按 path 树分组
  // 输入: /api/agent/command → segments = ['agent', 'command']
  // 输出: api.agent.command.post(body) = request<Res>('POST', '/api/agent/command', body)
  interface Node {
    children: Map<string, Node>
    methods: Map<string, Entry>
  }
  const root: Node = { children: new Map(), methods: new Map() }
  for (const e of entries) {
    const segments = e.path.split('/').filter((s) => s && s !== 'api')
    if (segments.length === 0) {
      // 路径根 /api → api.get 之类, 顺手丢掉
      skipped.push({ key: `${e.method} ${e.path}`, reason: 'path 仅 /api, 无分段' })
      continue
    }
    let node = root
    for (let i = 0; i < segments.length - 1; i++) {
      const seg = segments[i]
      let child = node.children.get(seg)
      if (!child) {
        child = { children: new Map(), methods: new Map() }
        node.children.set(seg, child)
      }
      node = child
    }
    const leaf = segments[segments.length - 1]
    // 同 path 不同 method (GET/POST /api/agent/sessions) 合并到同一 leaf
    // 节点, key = `<leaf>:<METHOD>` 防重复。
    const mkey = `${leaf}:${e.method}`
    if (node.methods.has(mkey)) {
      throw new Error(`[codegen] 路径冲突: ${e.path} (${e.method}) 重复登记 — 检查 RpcMethodMap`)
    }
    node.methods.set(mkey, e)
  }

  // 生成 stub
  const lines: string[] = []
  lines.push('// AUTO-GENERATED by scripts/generate-rpc-client.ts.')
  lines.push('// DO NOT EDIT. Run `pnpm run codegen:rpc` to regenerate.')
  lines.push('')
  lines.push('import { request } from "./apiBase.js";')
  lines.push('import type { RpcMethodMap } from "../../../shared/rpc.js";')
  lines.push('')
  lines.push('type _Map = RpcMethodMap;')
  lines.push('')
  lines.push('export const api = {')

  function emit(node: Node, indent: string) {
    // 先 children
    const childKeys = Array.from(node.children.keys()).sort()
    for (const k of childKeys) {
      lines.push(`${indent}${k}: {`)
      emit(node.children.get(k)!, indent + '  ')
      lines.push(`${indent}},`)
    }
    // 再 methods (同 leaf 多个 method 时, 多个 method 块会挨着生成,
    // TypeScript 不在意重复 key, 但为了可读, 合并到一个 { leaf: { m1, m2 } } 块)
    const methodsByLeaf = new Map<string, Entry[]>()
    for (const [mkey, e] of node.methods) {
      const leaf = mkey.split(':')[0]
      const arr = methodsByLeaf.get(leaf) ?? []
      arr.push(e)
      methodsByLeaf.set(leaf, arr)
    }
    for (const [leaf, entries] of Array.from(methodsByLeaf.entries()).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`${indent}${leaf}: {`)
      for (const e of entries) {
        const methodLower = e.method.toLowerCase()
        // 用 _Map 索引访问 RpcMethodMap, 避免 inline 类型与 single-source
        // 漂移. 索引 key = `"${METHOD} ${path}"` (与 RpcMethodMap key 同形).
        const mapKey = `"${e.method} ${e.path}"`
        const reqType = `_Map[${mapKey}]['request']`
        const resType = `_Map[${mapKey}]['response']`
        let argSig: string
        let callArgs: string
        if (e.requestType === 'undefined') {
          argSig = '()'
          callArgs = `request<${resType}>("${e.method}", "${e.path}")`
        } else {
          argSig = `(body: ${reqType})`
          callArgs = `request<${resType}>("${e.method}", "${e.path}", body)`
        }
        lines.push(`${indent}  ${methodLower}: ${argSig} => ${callArgs},`)
      }
      lines.push(`${indent}},`)
    }
  }

  emit(root, '  ')

  lines.push('} as const;')
  lines.push('')

  await writeFile(outPath, lines.join('\n'), 'utf-8')

  const relRpc = relative(repoRoot, rpcPath)
  const relOut = relative(repoRoot, outPath)
  console.log(`[codegen] ${entries.length} entries → ${relOut}`)
  for (const s of skipped) {
    console.warn(`[codegen] skip ${s.key}: ${s.reason}`)
  }
  console.log(`[codegen] source: ${relRpc}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
