/**
 * openccQueryBridge — connects zai's DefaultAgentRuntime.run() to
 * opencc's `query()`. Lazy-imports the bundled opencc-core.mjs,
 * translates zai QueryOptions → opencc QueryParams, attaches core
 * tools, streams SDKMessage → RuntimeEvent.
 *
 * Runtime path: zai /agent/prompt → DefaultAgentRuntime.run → here.
 */

import { existsSync } from 'node:fs'
import { resolve as pathResolve } from 'node:path'
import { pathToFileURL, fileURLToPath } from 'node:url'
import type { QueryOptions, OpenccAdapterConfig } from './types.js'
import type { RuntimeEvent } from './events.js'
import { buildOpenccQueryParams } from './buildOpenccQueryParams.js'
import { renderToolDescriptions } from './buildOpenccQueryParams.js'
import { translateSdkToRuntime } from './sdkEventAdapter.js'
import { getOpenccBuiltinTools } from '../tools/opencc/builtin.js'
import { toRuntimeErrorEvent, toAbortedEvent } from './streamAdapter.js'

// The bundled opencc core. Generated by scripts/bundle-opencc.ts
// (esbuild) from src/opencc-src/query.ts + transitive deps. Exposed
// via the package's `./opencc-core` export (see package.json
// `exports`). Consumers (this file, compat/tools/opencc/builtin.ts,
// compat/openccInit.ts) import it via the package path so we don't
// depend on the relative layout of dist/ subdirs.
const BUNDLE_URL = '@zn-ai/zn-agent-core/opencc-core'

let openccModulePromise: Promise<any> | null = null

/**
 * Translate a tool-callback RuntimeEvent into the ServerEvent shape the
 * eventBus (and downstream SSE) expects. Today the only callback used is
 * AskUserQuestion's `tool_use:ask_pending`, which must become a
 * `prompt.ask` ServerEvent for the frontend's QuestionCard to render
 * (useEventStream.ts:56 / eventSource.ts:35 only dispatch `prompt.ask`).
 *
 * Exported for unit testing — the production call site is the
 * `__zaiBridgeCtx.onYield` closure inside `runViaOpenccQuery`.
 *
 * Returns `undefined` when the event has no known ServerEvent mapping;
 * the caller should then either queue the raw event for later drainage
 * or emit it as-is.
 */
export function translateToolCallbackToServerEvent(
  ev: { type: string; [k: string]: unknown },
  sessionId: string,
): { type: 'prompt.ask'; sessionId: string; toolUseId: string; questions: unknown[]; metadata?: unknown } | undefined {
  if (ev.type === 'tool_use:ask_pending') {
    const askId = ((ev.id as string) ??
      (ev.toolUseId as string) ??
      '') as string
    return {
      type: 'prompt.ask',
      sessionId,
      toolUseId: askId,
      questions: (ev.questions as unknown[]) ?? [],
      ...(ev.metadata ? { metadata: ev.metadata } : {}),
    }
  }
  return undefined
}

async function importOpenccSrc() {
  if (openccModulePromise) return openccModulePromise
  // Resolve the package export to a concrete file URL so we can
  // check it exists (better error than "Cannot find module" from
  // deep inside Node's resolver).
  let url: string
  try {
    url = (await import.meta.resolve?.(BUNDLE_URL)) ?? BUNDLE_URL
  } catch {
    // import.meta.resolve may be unavailable in older runtimes;
    // fall through to a direct import.
    url = BUNDLE_URL
  }
  // Verify the resolved path is on disk. import.meta.resolve returns
  // a file:// URL when the target exists; otherwise it throws.
  if (url.startsWith('file://') && !existsSync(fileURLToPath(url))) {
    throw new Error(
      `[openccQueryBridge] opencc-core.mjs not found at ${url}. ` +
      `Run \`pnpm --filter @zn-ai/zn-agent-core build\` to (re)generate the bundle.`,
    )
  }
  openccModulePromise = import(BUNDLE_URL)
  return openccModulePromise
}

export async function* runViaOpenccQuery(
  opts: QueryOptions,
  config: OpenccAdapterConfig,
): AsyncIterable<RuntimeEvent> {
  const sessionId = opts.sessionId ?? opts.transcriptId ?? 'unknown'

  // 1. Pre-aborted.
  if (opts.abortSignal?.aborted) {
    yield toAbortedEvent({ sessionId, turnIndex: 0 }, String(opts.abortSignal.reason ?? 'aborted'))
    return
  }

  // 2. Translate params + attach core tools. buildOpenccQueryParams is
  // async because it dynamically imports opencc's `productionDeps()`
  // factory (avoiding Vite's static bundling of opencc-src).
  let params: any
  try {
    params = await buildOpenccQueryParams(opts, config)
  } catch (err) {
    yield toRuntimeErrorEvent(
      new Error(
        `[openccQueryBridge] failed to build QueryParams: ${(err as Error).message}`,
      ),
      { sessionId, turnIndex: 0 },
    )
    return
  }
  const zaiTools = (opts.tools ?? []) as any[]
  // Use opencc's BUILT-IN tools directly (Bash/Read/Edit/Write/
  // AskUserQuestion/Glob/Grep) instead of zai's wrapper layer.
  // See compat/tools/opencc/builtin.ts for trade-offs. The
  // `bridgeCtx` global lets the AskUserQuestion wrapper (which was
  // already constructed when getOpenccBuiltinTools() was first
  // called) access sessionId / askRegistry / onYield at call time.
  //
  // Tool events (e.g. tool_use:ask_pending from AskUserQuestion) are
  // pushed into pendingToolEvents. We drain this queue between
  // opencc stream events so they flow through translateRuntimeEvents
  // (which already handles tool_use:ask_pending → prompt.ask → SSE).
  const pendingToolEvents: Array<{ type: string; [k: string]: unknown }> = []
  const drainToolEvents = function* () {
    while (pendingToolEvents.length > 0) {
      const ev = pendingToolEvents.shift()!
      for (const out of translateSdkToRuntime(
        ev as unknown,
        { sessionId, turnIndex: 0, eventCounter: ++eventCounter },
      )) {
        yield out
      }
    }
  }
  ;(globalThis as any).__zaiBridgeCtx = {
    sessionId,
    askRegistry: config.askRegistry,
    abortSignal: opts.abortSignal,
    onYield: (ev: any) => {
      // CRITICAL: zai's tool callbacks (e.g. AskUserQuestion's
      // tool_use:ask_pending) fire SYNCHRONOUSLY before the tool
      // awaits. But the tool's await then blocks the bridge's
      // for-await on the opencc stream — so a queue drained
      // between opencc events never flushes until the tool returns
      // (which is when the user has already answered, too late).
      //
      // Workaround: the route attaches the ServerEventBus to
      // globalThis.__zaiEventBus at init time. We emit directly to
      // it so prompt.ask / tool_call events reach the SSE
      // immediately, while the tool is still blocked awaiting the
      // user's answer.
      //
      // CRITICAL (Bug B): the bus expects ServerEvent-shaped payloads,
      // not raw RuntimeEvent. Emitting `{type:'tool_use:ask_pending',
      // ...}` arrives at the SSE consumer with that exact event type —
      // but the frontend's useEventStream only dispatches
      // `prompt.ask` (useEventStream.ts:56 / eventSource.ts:35), so the
      // modal never opens. Mirror routes/agent.ts:252-269 and translate
      // ask_pending → prompt.ask here before emitting.
      const bus = (globalThis as any).__zaiEventBus
      if (bus && typeof bus.emit === 'function') {
        const translated = translateToolCallbackToServerEvent(ev, sessionId)
        if (translated) {
          bus.emit(translated)
          return
        }
        // Other RuntimeEvent types emitted from tool callbacks are
        // forwarded as-is for now. Today the only known caller is
        // AskUserQuestion (compat/tools/index.ts:326) which yields
        // tool_use:ask_pending; future zai-native tools using ctx.onYield
        // should add a translation branch in translateToolCallbackToServerEvent
        // rather than relying on raw forwarding.
        bus.emit({
          type: ev.type,
          sessionId,
          ...(ev.id ? { id: ev.id } : {}),
          ...(ev.toolUseId ? { toolUseId: ev.toolUseId } : {}),
          ...(ev.questions ? { questions: ev.questions } : {}),
          ...(ev.metadata ? { metadata: ev.metadata } : {}),
          ...(ev.toolName ? { toolName: ev.toolName } : {}),
          ...(ev.input ? { input: ev.input } : {}),
        })
      } else {
        // Fallback: queue. Drainage will happen on the next opencc
        // stream event. (Without __zaiEventBus, ask_pending won't
        // reach the frontend until the tool returns.)
        pendingToolEvents.push({ type: ev.type, ...ev })
      }
    },
  }
  const coreTools = await getOpenccBuiltinTools()
  // zai tools win on name collision.
  const toolMap = new Map<string, any>()
  for (const t of coreTools) toolMap.set(t.name, t)
  for (const t of zaiTools) toolMap.set(t.name ?? t.name, t)
  params.tools = Array.from(toolMap.values())
  // Mirror tools onto toolUseContext.options.tools so opencc internals
  // that read `state.toolUseContext.options.tools` see them.
  if (params.toolUseContext?.options) {
    params.toolUseContext.options.tools = params.tools
  }
  // zai patch: vendor's `utils/api.ts:221` derives each tool's LLM-facing
  // description by awaiting `tool.prompt({ agents, ... })`. We can't go
  // through vendor's `toolToAPISchema` because zai bypasses vendor's
  // claude.ts and uses its own modelCaller (`modelCaller.ts:359-365`)
  // which reads the static `t.description` field. Render every tool's
  // dynamic description here and mutate back so the LLM sees the
  // AgentTool listing the actual sub-agents it can dispatch. Especially
  // important for AgentTool — without this, the LLM has no idea which
  // `subagent_type` values are valid.
  await renderToolDescriptions(params.tools, {
    getToolPermissionContext: async () =>
      (params.toolUseContext?.getToolPermissionContext?.()) ?? {},
    agents:
      params.toolUseContext?.options?.agentDefinitions?.activeAgents ?? [],
    allowedAgentTypes:
      params.toolUseContext?.options?.agentDefinitions?.allowedAgentTypes,
  })

  // 3. Lazy import opencc-src.
  let openccQuery: any
  try {
    const mod = await importOpenccSrc()
    openccQuery = mod.query
  } catch (err) {
    yield toRuntimeErrorEvent(
      new Error(
        `[openccQueryBridge] failed to import opencc-src/query: ${(err as Error).message}. ` +
          `Ensure bun-protocol.mjs is loaded via \`tsx --import\` and any hand-stubs are in place.`,
      ),
      { sessionId, turnIndex: 0 },
    )
    return
  }

  // 4. Call opencc + stream forward.
  let eventCounter = 0
  // zai patch: track block indices already streamed via the stream_event
  // path so the terminal `assistant` Message's synthesized primitives
  // don't double-render at the SSE consumer (see sdkEventAdapter.ts:178-246
  // for the synthesis branch and the comment block on lines 30-43 for
  // the dedupe rationale). Reset per assistant message_start
  // (sdkEventAdapter:109-111).
  const streamedBlockIndices = new Set<number>()
  try {
    const stream: AsyncIterable<unknown> = openccQuery(params)
    // Watchdog: after we see a message_stop or message_delta (the natural
    // "end of LLM output" signals opencc emits), if no further opencc
    // events arrive within WATCHDOG_MS, the opencc loop has stalled (e.g.
    // model produced end_turn but queryLoop's natural exit path didn't
    // fire, or a tool result fed into a continuation-nudge loop).
    //
    // Critical: when translateRuntimeEvents in routes/agent.ts sees
    // message_stop it yields runtime.done and the consumer's outer
    // for-await breaks, which calls .return() on THIS generator and
    // freezes the while loop at the next iter.next() — so we can't
    // rely on a Promise.race inside the loop to fire. Instead, the
    // timer is armed here and on fire, emits runtime.done via the same
    // __zaiEventBus side-channel used by AskUserQuestion. Without this
    // watchdog, the frontend stays stuck on "calling" forever.
    const iter = stream[Symbol.asyncIterator]()
    const WATCHDOG_MS = Number(process.env.ZAI_OPENCC_WATCHDOG_MS ?? 300_000)
    const TOOL_RESULT_TIMEOUT_MS = Number(
      process.env.ZAI_TOOL_RESULT_TIMEOUT_MS ?? 60_000,
    )
    let watchdogTimer: ReturnType<typeof setTimeout> | null = null
    let toolResultTimer: ReturnType<typeof setTimeout> | null = null
    const disarmWatchdog = () => {
      if (watchdogTimer) {
        clearTimeout(watchdogTimer)
        watchdogTimer = null
      }
      if (toolResultTimer) {
        clearTimeout(toolResultTimer)
        toolResultTimer = null
      }
    }
    const bus = (globalThis as any).__zaiEventBus
    // Per-bridge map of tool_use_id → tool name. opencc's tool_result
    // content blocks don't carry the name; we remember it from the
    // matching tool_use content_block_start so the runtime.tool_result
    // SSE event includes the correct toolName (otherwise
    // translateRuntimeEvents in routes/agent.ts defaults to "unknown"
    // and the frontend's upsertToolCall overwrites the stored
    // "Bash"/"Read"/etc. label).
    const toolNameByUseId = new Map<string, string>()
    const emitForcedCompletion = (timeoutMs: number, trigger: string) => {
      console.warn(
        `[openccQueryBridge] watchdog tripped after ${trigger} with ` +
          `no tool result for ${timeoutMs}ms — emitting runtime.done + tool_result for ${toolNameByUseId.size} pending tool(s)`,
      )
      if (bus && typeof bus.emit === 'function') {
        bus.emit({
          type: 'runtime.done',
          sessionId,
          turnIndex: 0,
          eventId: `evt-watchdog-${Date.now()}`,
          ts: Date.now(),
          forced: true,
        })
        for (const [toolUseId, toolName] of toolNameByUseId) {
          bus.emit({
            type: 'runtime.tool_result',
            sessionId,
            turnIndex: 0,
            eventId: `evt-watchdog-tool-${toolUseId}`,
            ts: Date.now(),
            toolUseId,
            toolName,
            output: `[watchdog] opencc stalled for ${timeoutMs}ms after ${trigger} — tool execution did not return a result. The bridge forced runtime.done; the LLM did not see a tool_result for this call.`,
            isError: true,
          })
        }
      }
    }
    const armToolResultWatchdog = () => {
      if (
        TOOL_RESULT_TIMEOUT_MS <= 0 ||
        toolResultTimer ||
        toolNameByUseId.size === 0
      ) {
        return
      }
      toolResultTimer = setTimeout(() => {
        emitForcedCompletion(TOOL_RESULT_TIMEOUT_MS, 'tool_use')
        toolResultTimer = null
      }, TOOL_RESULT_TIMEOUT_MS)
    }
    while (true) {
      if (opts.abortSignal?.aborted) {
        disarmWatchdog()
        yield toAbortedEvent({ sessionId, turnIndex: 0 }, String(opts.abortSignal.reason ?? 'aborted'))
        return
      }
      const sdkMsg: IteratorResult<unknown, unknown> = await iter.next()
      if (sdkMsg.done) {
        disarmWatchdog()
        break
      }
      // Drain any tool events buffered by tool callbacks (e.g.
      // AskUserQuestion's tool_use:ask_pending) BEFORE the next
      // opencc stream event. The route's translateRuntimeEvents
      // already maps these to prompt.ask / tool_call SSE events.
      for (const ev of drainToolEvents()) {
        yield ev
      }
      for (const ev of translateSdkToRuntime(sdkMsg.value, { sessionId, turnIndex: 0, eventCounter, toolNameByUseId, streamedBlockIndices })) {
        yield ev
        eventCounter++
      }
      if (process.env.ZAI_DEBUG === '1') {
        const sdkType = (sdkMsg.value as any)?.type
        const msgStr = sdkType === 'user' ? JSON.stringify((sdkMsg.value as any)?.message?.content ?? []).slice(0, 300) : ''
        const asstStr = sdkType === 'assistant' ? JSON.stringify((sdkMsg.value as any)?.message?.content ?? []).slice(0, 300) : ''
        const cbType = (sdkMsg.value as any)?.content_block?.type
        console.log('[bridge.iter] sdkType=', sdkType, 'cbType=', cbType, msgStr, asstStr)
      }
      const sdkValue = sdkMsg.value as any
      const sdkType = sdkValue?.type
      const contentBlock = sdkValue?.content_block
      if (sdkType === 'content_block_start' && contentBlock?.type === 'tool_use') {
        armToolResultWatchdog()
      }
      const hasToolResult =
        sdkType === 'tool_result' ||
        (sdkType === 'user' &&
          Array.isArray(sdkValue?.message?.content) &&
          sdkValue.message.content.some((block: any) => block?.type === 'tool_result'))
      if (hasToolResult && toolResultTimer) {
        clearTimeout(toolResultTimer)
        toolResultTimer = null
      }
      // Arm the watchdog after any "end of LLM output" signal:
      //   - message_stop  (Anthropic stop primitive)
      //   - message_delta (last message_delta carries stop_reason)
      // opencc doesn't always yield message_stop through the bridge
      // (sometimes it wraps the stop in an assistant message and
      // just closes the iterator), so trigger on either to be safe.
      // On any further event from the next turn, disarm so a long
      // follow-up turn doesn't trip the watchdog.
      if (sdkType === 'message_stop' || sdkType === 'message_delta') {
        if (WATCHDOG_MS > 0 && !watchdogTimer) {
          watchdogTimer = setTimeout(() => {
            emitForcedCompletion(WATCHDOG_MS, sdkType)
            watchdogTimer = null
          }, WATCHDOG_MS)
        }
      } else {
        // Disarm on any further event so a long next turn doesn't trip.
        disarmWatchdog()
      }
    }
    disarmWatchdog()
    // Final drain — any tool events buffered after the last opencc
    // event (e.g. AskUserQuestion yielded ask_pending during its
    // call) need to flush before the bridge returns.
    for (const ev of drainToolEvents()) {
      yield ev
    }
  } catch (err) {
    yield toRuntimeErrorEvent(err, { sessionId, turnIndex: 0 })
  }
}
