/**
 * Hand-stub for opencc-src build artifacts that don't exist in the
 * vendored snapshot. opencc vendor expects these to be generated by
 * their internal build pipeline; we never ran it. Without these
 * stubs, even the lazy-import of opencc-src/query.js fails on the
 * very first transitive import (`../integrations/generated/...`).
 *
 * Each export is a placeholder matching the *shape* opencc uses it
 * for, not a real implementation:
 *
 *   - PROVIDER_DESCRIPTOR constant arrays → empty arrays / {} objects
 *   - generated event types → empty classes for `instanceof` checks
 *   - auth types → empty objects / strings
 *
 * Wire this via vitest.config.ts `resolve.alias` regex entries:
 *
 *   { find: /integrations\/generated\/.*\.generated\.js$/,
 *     replacement: '...dangling-shims/opencc-generated.ts' },
 *   { find: /types\/generated\/.*\.ts$/,
 *     replacement: '...dangling-shims/opencc-generated.ts' },
 *
 * Same aliases should also be wired into tsx --import hooks for
 * non-vitest runs (out of scope here — see bun-protocol.mjs).
 */

export const ANTHROPIC_PROXY_DESCRIPTORS: readonly unknown[] = []
export const GATEWAY_DESCRIPTORS: readonly unknown[] = []
export const PROVIDER_PRESET_MANIFEST: Record<string, unknown> = {}
export const VENDOR_DESCRIPTORS: readonly unknown[] = []

// Generated event classes (opencc analytics uses them as types +
// for `instanceof` discrimination). Empty classes are safe — code
// only ever checks `event instanceof ClaudeCodeInternalEvent`.
export class ClaudeCodeInternalEvent {}
export class GrowthbookExperimentEvent {}

// Auth-related generated types.
export interface EnvironmentMetadata {
  environment: string
  region?: string
}
export interface PublicApiAuth {
  apiKey?: string
  oauthToken?: string
}
