// AUTO-GENERATED by scripts/generate-rpc-client.ts.
// DO NOT EDIT. Run `pnpm run codegen:rpc` to regenerate.

import { request } from "./apiBase.js";
import type { RpcMethodMap } from "../../../shared/rpc.js";

type _Map = RpcMethodMap;

export const api = {
  agent: {
    command: {
      post: (body: _Map["POST /api/agent/command"]['request']) => request<_Map["POST /api/agent/command"]['response']>("POST", "/api/agent/command", body),
    },
    prompt: {
      post: (body: _Map["POST /api/agent/prompt"]['request']) => request<_Map["POST /api/agent/prompt"]['response']>("POST", "/api/agent/prompt", body),
    },
    sessions: {
      get: () => request<_Map["GET /api/agent/sessions"]['response']>("GET", "/api/agent/sessions"),
      post: (body: _Map["POST /api/agent/sessions"]['request']) => request<_Map["POST /api/agent/sessions"]['response']>("POST", "/api/agent/sessions", body),
    },
  },
  weixin: {
    setup: {
      cancel: {
        post: (body: _Map["POST /api/weixin/setup/cancel"]['request']) => request<_Map["POST /api/weixin/setup/cancel"]['response']>("POST", "/api/weixin/setup/cancel", body),
      },
      confirm: {
        post: (body: _Map["POST /api/weixin/setup/confirm"]['request']) => request<_Map["POST /api/weixin/setup/confirm"]['response']>("POST", "/api/weixin/setup/confirm", body),
      },
      poll: {
        get: (body: _Map["GET /api/weixin/setup/poll"]['request']) => request<_Map["GET /api/weixin/setup/poll"]['response']>("GET", "/api/weixin/setup/poll", body),
      },
      start: {
        post: (body: _Map["POST /api/weixin/setup/start"]['request']) => request<_Map["POST /api/weixin/setup/start"]['response']>("POST", "/api/weixin/setup/start", body),
      },
    },
    connect: {
      post: (body: _Map["POST /api/weixin/connect"]['request']) => request<_Map["POST /api/weixin/connect"]['response']>("POST", "/api/weixin/connect", body),
    },
    disconnect: {
      post: (body: _Map["POST /api/weixin/disconnect"]['request']) => request<_Map["POST /api/weixin/disconnect"]['response']>("POST", "/api/weixin/disconnect", body),
    },
    reload: {
      post: (body: _Map["POST /api/weixin/reload"]['request']) => request<_Map["POST /api/weixin/reload"]['response']>("POST", "/api/weixin/reload", body),
    },
    status: {
      get: () => request<_Map["GET /api/weixin/status"]['response']>("GET", "/api/weixin/status"),
    },
  },
  cli: {
    get: () => request<_Map["GET /api/cli"]['response']>("GET", "/api/cli"),
  },
  health: {
    get: () => request<_Map["GET /api/health"]['response']>("GET", "/api/health"),
  },
} as const;
