// AUTO-GENERATED by scripts/generate-rpc-client.ts.
// DO NOT EDIT. Run `pnpm run codegen:rpc` to regenerate.

import { request } from "./apiBase.js";
import type { RpcMethodMap } from "../../../shared/rpc.js";

type _Map = RpcMethodMap;

export const api = {
  agent: {
    command: {
      post: (body: _Map["POST /api/agent/command"]['request']) => request<_Map["POST /api/agent/command"]['response']>("POST", "/api/agent/command", body),
    },
    prompt: {
      post: (body: _Map["POST /api/agent/prompt"]['request']) => request<_Map["POST /api/agent/prompt"]['response']>("POST", "/api/agent/prompt", body),
    },
    sessions: {
      get: () => request<_Map["GET /api/agent/sessions"]['response']>("GET", "/api/agent/sessions"),
      post: (body: _Map["POST /api/agent/sessions"]['request']) => request<_Map["POST /api/agent/sessions"]['response']>("POST", "/api/agent/sessions", body),
    },
  },
  cli: {
    get: () => request<_Map["GET /api/cli"]['response']>("GET", "/api/cli"),
  },
  health: {
    get: () => request<_Map["GET /api/health"]['response']>("GET", "/api/health"),
  },
} as const;
